name: ping health endpoint everyday at 4pm

on:
  workflow_dispatch: # Allows you to trigger it manually for testing

jobs:
  ping_server:
    name: send get request to health endpoint
    runs-on: ubuntu-latest
    steps:
      - name: Log Success
        run: echo "Ping to health endpoint was successful."
